name: Deploy to Vercel

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production  # Required if using GitHub Environments

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Link Vercel Project
        run: |
          rm -rf .vercel  # Clear existing config
          vercel link --yes --token=${{ secrets.VERCEL_TOKEN }} \
            --project=${{ secrets.VERCEL_PROJECT_ID }} \
            --scope=${{ secrets.VERCEL_TEAM }}

      - name: Pull Environment Variables
        run: |
          vercel pull --yes --environment=production \
            --token=${{ secrets.VERCEL_TOKEN }} \
            --scope=${{ secrets.VERCEL_TEAM }}
          vercel env pull .env.production --environment=production \
            --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

      - name: Deploy to Production
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
