name: Deploy to Vercel

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Force Link Project
        run: |
          rm -rf .vercel
          echo '{
            "projectId": "${{ secrets.VERCEL_PROJECT_ID }}",
            "orgId": "${{ secrets.VERCEL_ORG_ID }}"
          }' > .vercel/project.json

      - name: Pull Environment
        run: |
          vercel pull --yes --environment=production \
            --token=${{ secrets.VERCEL_TOKEN }} \
            --scope=${{ secrets.VERCEL_TEAM }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
